
<?php

    echo "<h1 style='font-family: initial;font-style: italic;font-size: 50px;margin-bottom: 30px;text-align: left;color: rgb(177, 46, 49);'>".$this->course[0]['course'].'</h1><br />';

    if($this->type == 1){
      echo "<a class='btn btn-danger' style='float: right;margin-right: 120px;' href='".$this->baseUrl()."/course/delete/id_cours/".$this->course[0]['id_cours']."'> Delete </a>&nbsp<a class='btn btn-info' style='float: right;margin-right: 50px;' href='".$this->baseUrl()."/course/edit/id_cours/".$this->course[0]['id_cours']."'> Edit </a>  &nbsp<br />";
    }

    echo "<h1 style='margin-top: -50px;font-style: italic;color: rgb(177, 46, 49);'> Viewed By : ".$this->course_num_views."</h1>";
    echo "<br /><label style='font-family: initial;font-style: italic; font-weight: bold;font-size: 20px;color: #66CCCC;'> Course Image: </label><h3>";
    echo "<br /><img style='margin: 20px; width: 850px;height: 300px;' src='".$this->baseUrl()."/images/courses/".$this->course[0]['cours_image']."'/>";
    
    echo "<br /><label style='font-family: initial;font-style: italic; font-weight: bold;font-size: 20px;color: #66CCCC;'> Course Description : </label><h3 style='margin: 20px;font-size: 20px;'>".$this->course[0]['cours_desc'].'</h3><br /></div><br>';

?>
<div class="allcontain">
<table>
<tr>
<td bgcolor="">
<div class="typemat">
    <?php
	foreach ($this->typematerials as $tymat){
              // ".$tymat['id_type']." :-  
            echo "<br/><a href='".$this->baseUrl()."/materials/single/course_id/".$this->course_id."/id_type/".$tymat['id_type']."'><label style='font-family: initial;font-style: italic; font-weight: bold;font-size: 20px;color:rgb(40, 110, 10);''>*&nbsp;&nbsp;".$tymat['contain_type'].':</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(</a>';
            echo "<a href='".$this->baseUrl()."/typematerials/edit/course_id/".$this->course_id."/id_type/".$tymat['id_type']."'>"
              . " Edit </a> "."<a href='".$this->baseUrl()."/typematerials/delete/course_id/".$this->course_id."/id_type/".$tymat['id_type']."'> <font color='red'>Delete </font>)</a> <br/><br/><br/>";
	}
        
    ?>
</div>
</td>

<td>
<div class="typeup">
    <?php
      $upimage=0;
      $upvideo=0;
      $upword=0;
      $upppt=0;
      $uppdf=0;
      $totalupload=0;
      foreach ($this->typeuploadss as $tyup){
        // ".$tyup['id_up']." :-  
          echo "<a href='".$this->baseUrl()."/materials/single/course_id/".$this->course_id."/id_type/".$this->id_type."/id_up/".$tyup['id_up']."'>"
                  . "<label style='font-family: initial;font-style: italic; font-weight: bold;font-size: 20px;color:rgb(40, 110, 10);''>#&nbsp;&nbsp;".$tyup['contain_upload'].'&nbsp;:-</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a><br/><br/>';

           if($this->admin=="admin" ){        
              echo "(<a href='".$this->baseUrl()."/typeuploads/edit/course_id/".$this->course_id."/id_type/".$this->id_type."/id_up/".$tyup['id_up']."'>"
                . " Edit </a><a href='".$this->baseUrl()."/typeuploads/delete/course_id/".$this->course_id."/id_type/".$this->id_type."/id_up/".$tyup['id_up']."'> &nbsp;&nbsp;&nbsp;&nbsp;<font color='red'>Delete </font>)</a>";
              if($tyup['show']=="show"){
                  echo "&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<a href='".$this->baseUrl()."/typeuploads/hidden/course_id/".$this->course_id."/id_type/".$this->id_type."/id_up/".$tyup['id_up']."'>(Show </a> ";
              }
              if($tyup['show']=="hidden"){
                  echo "&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<a href='".$this->baseUrl()."/typeuploads/show/course_id/".$this->course_id."/id_type/".$this->id_type."/id_up/".$tyup['id_up']."'>(Hidden </a> ";
              }
              if($tyup['lock']=="lock"){
                  echo "<a href='".$this->baseUrl()."/typeuploads/unlock/course_id/".$this->course_id."/id_type/".$this->id_type."/id_up/".$tyup['id_up']."'> &nbsp;&nbsp;&nbsp;&nbsp;<font color='red'> Lock </font>)</a><br/><br/>";
              }
              if($tyup['lock']=="unlock"){
                  echo "<a href='".$this->baseUrl()."/typeuploads/lock/course_id/".$this->course_id."/id_type/".$this->id_type."/id_up/".$tyup['id_up']."'> &nbsp;&nbsp;&nbsp;&nbsp;<font color='red'> UNLock </font>)</a><br/><br/>";
              }
        }
         
          if(($tyup['contain_upload'] == 'image') or($tyup['contain_upload'] == 'Image') ) { 
              if($tyup['show']=="hidden"){
                foreach ($this->typeimages as $tyimage){
                      if($tyimage['mat_image'] != NULL){
                          $upimage+=1;

                        if($tyup['lock']=="lock"){  
                            echo "<a href='".$this->baseUrl()."/materials/showsingle/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyimage['id_mat']."'>"
                                    . "<img  width='150' height='150' src='".$this->baseUrl()."/images/materials/".$tyimage['mat_image']."'/>"
                                    . "</a>";
                          } else{
                            echo "<img  width='150' height='150' src='".$this->baseUrl()."/images/materials/".$tyimage['mat_image']."'/>"
                                    . "</a>";
                          }   
                        if($this->admin=="admin" ){
                            echo "<a href='".$this->baseUrl()."/materials/delete/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyimage['id_mat']."/id_up/".$tyup['id_up']."'>"
                                . "<font color='red'>( Delete )</font></a>";
                         } 
                        echo "&nbsp;&nbsp;";       
                      }
                  }
                   echo "<br/><br/><lable class='nnumdown'>".$upimage."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/up.png'/>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<lable>".$this->numdownimage."</lable>
                <img  width='30' height='30' src='".$this->baseUrl()."/images/down.png'/><br/>";
            
        }else {
          echo "<div class='fpwivmessag'><br/>Sorry,Not Show Image ???<br/></div> ";
        } 
      }

          if(($tyup['contain_upload'] == 'video') or($tyup['contain_upload'] == 'Video') ) { 
             if($tyup['show']=="hidden"){ 
              foreach ($this->typevides as $tyvideo){
                    if($tyvideo['mat_video'] != NULL){
                        $upvideo+=1;
                        if($tyup['lock']=="lock"){ 
                          echo "<a href='".$this->baseUrl()."/materials/showvideo/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyvideo['id_mat']."'><img  width='150' height='150' src='".$this->baseUrl()."/videos/video.jpg'/></a>&nbsp;&nbsp;";
                         } else{
                          echo "<img  width='150' height='150' src='".$this->baseUrl()."/videos/video.jpg'/></a>&nbsp;&nbsp;";
                         }
                      if($this->admin=="admin" ){
                          echo "<a href='".$this->baseUrl()."/materials/delete/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyvideo['id_mat']."/id_up/".$tyup['id_up']."'>"
                              . "<font color='red'>( Delete )</font></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                        }      
                    }
                }
                 echo "<br/><br/><lable class='nnumdown'>".$upvideo."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/up.png'/>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<lable>".$this->numdownvideo."</lable>
              <img  width='30' height='30' src='".$this->baseUrl()."/images/down.png'/><br/>";
             }else {
                echo "<div class='fpwivmessag'><br/>Sorry,Not Show Video ???<br/></div> ";
              } 
            }  
          if(($tyup['contain_upload'] == 'PDF') or($tyup['contain_upload'] == 'pdf') ) { 
              if($tyup['show']=="hidden"){
                foreach ($this->typePDFs as $typdf){
                      if($typdf['mat_pdf'] != NULL){
                          $uppdf+=1;
                         if($tyup['lock']=="lock"){ 
                            echo "<a href='".$this->baseUrl()."/materials/pdfdown/pdfs"."/".$typdf['mat_pdf']."'>".$typdf['mat_pdf']."</a>";
                        
                        echo "&nbsp;&nbsp;<a href='".$this->baseUrl()."/materials/pdfdowntest"."/course_id/".$this->course_id."/id_type/".$this->id_type."/".$typdf['mat_word']."'>(Download)</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                      }else{
                        echo "<a href='#'>".$typdf['mat_pdf']."</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                      }
                      if($this->admin=="admin" ){
                          echo "<a href='".$this->baseUrl()."/materials/editpptpdfword/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$typdf['id_mat']."'>( Update</a>";

                           echo "&nbsp;&nbsp;<a href='".$this->baseUrl()."/materials/delete/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$typdf['id_mat']."/id_up/".$tyup['id_up']."'>"
                                . "<font color='red'>Delete )</font></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                          }      
                      }
                  }
                   echo "<br/><br/><lable class='nnumdown'>".$uppdf."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/up.png'/>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<lable>".$this->numdownpdf."</lable>
                <img  width='30' height='30' src='".$this->baseUrl()."/images/down.png'/><br/>";
              }else {
                echo "<div class='fpwivmessag'><br/>Sorry,Not Show PDF ???<br/></div> ";
              } 
            }           
          if(($tyup['contain_upload'] == 'Word') or($tyup['contain_upload'] == 'word') ) { 
            if($tyup['show']=="hidden"){    
              foreach ($this->typewords as $tyword){
                    if($tyword['mat_word'] != NULL){
                        $upword+=1;
                        if($tyup['lock']=="lock"){                       
                          echo "<a href='".$this->baseUrl()."/materials/worddown/Words"."/".$tyword['mat_word']."'>".$tyword['mat_word']."</a>";

                          echo "&nbsp;&nbsp;<a href='".$this->baseUrl()."/materials/worddowntest"."/course_id/".$this->course_id."/id_type/".$this->id_type."/".$tyword['mat_word']."'>(Download )</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                         }else{
                          echo "<a href='#'>".$tyword['mat_word']."</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                         } 
                     if($this->admin=="admin" ){ 
                      echo "<a href='".$this->baseUrl()."/materials/editpptpdfword/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyword['id_mat']."'>( Update</a>";

                        echo "&nbsp;&nbsp;<a href='".$this->baseUrl()."/materials/delete/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyword['id_mat']."/id_up/".$tyup['id_up']."'>". "<font color='red'> Delete </font>)</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
                       } 
                    }
                }
                 echo "<br/><br/><lable class='nnumdown'>".$upword."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/up.png'/>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<lable>".$this->numdownword."</lable>
              <img  width='30' height='30' src='".$this->baseUrl()."/images/down.png'/><br/>";
          }else {
                echo "<div class='fpwivmessag'><br/>Sorry,Not Show Word ???<br/></div> ";
              } 
          } 
          if(($tyup['contain_upload'] == 'PPT') or($tyup['contain_upload'] == 'ppt') ) { 
           if($tyup['show']=="hidden"){
              foreach ($this->typePPTs as $typpt){
                    if($typpt['mat_ppt'] != NULL){
                        $upppt+=1;
                        if($tyup['lock']=="lock"){ 
                          echo "<a href='".$this->baseUrl()."/materials/pptdown/ppts"."/".$typpt['mat_ppt']."'>".$typpt['mat_ppt']."</a>";
                          
                          echo "&nbsp;&nbsp;<a href='".$this->baseUrl()."/materials/pptdowntest"."/course_id/".$this->course_id."/id_type/".$this->id_type."/".$typpt['mat_word']."'>(Download)</a>&nbsp;";
                         }else{
                          echo "<a href='#'>".$typpt['mat_ppt']."</a>&nbsp;&nbsp;&nbsp;";
                         } 
                      if($this->admin=="admin" ){ 
                        echo "<a href='".$this->baseUrl()."/materials/editpptpdfword/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$typpt['id_mat']."'>( Update</a>";

                        echo "&nbsp;&nbsp;<a href='".$this->baseUrl()."/materials/delete/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$typpt['id_mat']."/id_up/".$tyup['id_up']."'>"
                              . "<font color='red'> Delete )</font></a>&nbsp;&nbsp;&nbsp;&nbsp;";
                        }      
                    }
                }
                 echo "<br/><br/><lable class='nnumdown'>".$upppt."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/up.png'/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<lable>".$this->numdownppt."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/down.png'/><br/>";
          }else {
                echo "<div class='fpwivmessag'><br/>Sorry,Not Show PPT ???<br/></div>";
              } 
          }           
          
          
         echo "<br/><hr/>";
      }

  ?>  
</td>
</div>
<tr>
<td >
  <br/><br/><label style="font-family: initial;font-style: italic; font-weight: bold;font-size: 20px;color:rgb(40, 110, 10);">Total Upload/Download</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<td>

 <?php
 echo "<div class='totalupload'>";
  $totalupload=$upimage+$upvideo+$uppdf+$upword+$upppt;
  echo "</div>";
echo "<br/><br/><label style='font-family: initial;font-style: italic; font-weight: bold;font-size: 20px;color:rgb(40, 110, 10);'class='nnumdown'>".$totalupload."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/up.png'/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<lable>".$this->totaldownload."</lable><img  width='30' height='30' src='".$this->baseUrl()."/images/down.png'/><br/>";
?>
</div>
</td>
</tr>
</table>
  <hr/>
